# Generated by Django 6.0 on 2026-03-15 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grievance_assigned_user_grievance_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statuslog',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
